name: Create Release

on :
  pull_request:
  push:
    branches:
     - master


jobs:
  build:

    runs-on: ubuntu-latest

    #using https://github.com/anothrNick/github-tag-action

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false


