name: Android Format Code

on :
  pull_request:
  push:

jobs:
  code_formatting_job:
    name: Code Formatting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Debug ktlint
        run: ./gradlew ktlintDebugCheck --continue

      - name: Upload ktlint Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ktlint-report
          path: '**/build/reports/ktlint'